/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_penship_cobaopencv_FaceDetector */

using namespace cv;
#ifndef _Included_com_penship_cobaopencv_FaceDetector
#define _Included_com_penship_cobaopencv_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_penship_cobaopencv_FaceDetector
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);
JNIEXPORT void JNICALL Java_com_penship_cobaopencv_FaceDetector_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
